name: NPM PROJECT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_TOKEN}}
      # ============= InvisiRisk Setup End =============

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build