name: Rust CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  checks: write
  actions: read
  contents: read
  id-token: write
 
env:
  CARGO_TERM_COLOR: always
 
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
 
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
      # ============= InvisiRisk Setup End =============
      
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
 
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
 
      - name: Check formatting
        run: cargo fmt --check
 
      - name: Lint with Clippy
        run: cargo clippy -- -D warnings
 
      - name: Build
        run: cargo build --verbose
 
      - name: Run tests
        run: cargo test --verbose